services:
  mysql:
    image: mysql:8
    command: --max_allowed_packet=325058560 --lower_case_table_names=2
    volumes:
      - .docker-dev/.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_technique
      - MYSQL_PASSWORD=root
    ports:
      - 3344:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql # 🔗 Adminer attend que MySQL soit prêt

  app:
    build: .docker-dev/app
    ports:
      - 8080:8000
    environment:
      - IS_DOCKER=1
    links:
      - mysql
      - elasticsearch
    volumes:
      - .:/var/application

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15676:15672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - http.port=9200
      - ES_JAVA_OPTS=-Xms2g -Xmx8g
